In [6]:
import numpy as np
# Numpy = Numerical python

In [12]:
# creation of array
# Numpy arrays are homogeneous in  nature and numpy is far better optimized than list in python
arr=np.array([1,2,6,3,4]) # numpy array
# li=[3,6,1,4] #list

In [16]:
print(arr,type(arr),arr.dtype,arr.shape)
# .dtype : tells data type and .shape : tells dimension of array
# print(li,type(li))

[1 2 6 3 4] <class 'numpy.ndarray'> int64 (5,)


In [19]:
# 2d array
arr2D=np.array([[1,2,3],[7,7,4],[11,5,6],[56,34,12]])
print(arr2D,arr2D.dtype,arr2D.shape)

[[ 1  2  3]
 [ 7  7  4]
 [11  5  6]
 [56 34 12]] int64 (4, 3)


### methods to create numpy arrays

In [26]:
# np.zeros : take dimension of array and create an array filled with 0s
arr_0=np.zeros((5,3),dtype="int64")
print(arr_0,arr_0.shape,arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] (5, 3) int64


In [28]:
# np.ones : same as zeros but pre-filled with 1s
arr_1=np.ones((4,5),dtype="int64")
print(arr_1,arr_1.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] (4, 5)


In [31]:
# np.full : provide choice to fill array
arr3=np.full((5,5),3.14)
print(arr3,arr3.dtype)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] float64


In [33]:
# np.eye : used to craete identity matrix
identity=np.eye((4))
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [59]:
# np.arange : np.arange(start,end,step)
arr4=np.arange(1,100,2)
print(arr4)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [66]:
# np.linspace(start,end,num) ; num : single number not tuple or dimension like(3,4)
# idea is to divide a range into a specific number of equal sub-intervals.
# interval/step size = Math.floor((stop-start)/num-1)
arr5=np.linspace(1,100,8,dtype="int64")
print(arr5)

[  1  15  29  43  57  71  85 100]


### useful methods

In [73]:
#reshaping : possible only for compatible types means total ele in original and reshape must be same eg 3x2 : 1x6,6x1,2x3
arr6=np.full((3,4),20,dtype="int64")
print(arr6,arr6.shape)
reshaped_arr=arr6.reshape((6,2)) # 3x4 : 12x1 , 1x12,4x3,6x2,2x6
print(reshaped_arr)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]] (3, 4)
[[20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]
 [20 20]]


In [84]:
# indexing on np arrays
arr=np.array([4,5,3,6,1])
print(arr[0],arr[3])
# in 2d array
arr=np.linspace(1,100,6,dtype="int64")

arr=arr.reshape((3,2))
print(arr)
print(arr[0][1],arr[2][1])


4 6
[[  1  20]
 [ 40  60]
 [ 80 100]]
20 100


In [85]:
# fancy indexing : access vals by indices at a time
arr=np.array([6,5,8,1,12,34])
idx=[0,4,2,5]
print(arr[idx])

[ 6 12  8 34]


In [89]:
# boolean indexing or conditional indexing
print(arr[ arr%2==0])
print(arr[arr>=10])

[ 6  8 12 34]
[12 34]


In [92]:
# slicing in np arrays
arr=np.array([3,8,5,6,3,4,10])
print(arr[::2])
print(arr[:3])
print(arr[3:6])
print(arr[:])

[ 3  5  3 10]
[3 8 5]
[6 3 4]
[ 3  8  5  6  3  4 10]


In [95]:
# slicing in np arrays do not create copy of original array unlike python list
# view slicing : np array & copy slicing in python list
# changing in elements of np array will reflect on original array since they do not create copy unlike python list
#-------(COPY SLICING)---in python list---------
li=[1,2,3,4,5]
sub_list=li[1:4]
sub_list[0]=100
print(li)
print(sub_list)

#----in numpy arrays------(VIEW SLICING)
# if we require to do not apply changes on original array then we can use .copy() method in sub array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:4]
sub_arr[0]=100
print(arr)
print(sub_arr)

[1, 2, 3, 4, 5]
[100, 3, 4]
[  1 100   3   4   5]
[100   3   4]
