In [1]:
import numpy as np

In [2]:
arr=np.array([4,7,8,3,1,7,7,9,6,5])

In [3]:
print(np.sum(arr))
print(np.prod(arr))
print(np.std(arr))
print(np.var(arr))
print(np.mean(arr))
print(np.sqrt(arr))
print(np.square(arr))
print(np.pow(arr,0)) # cal power here power=0
print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr)) # return index of max val
print(np.argmin(arr)) # return index of min val
print(np.median(arr))

57
8890560
2.3259406699226015
5.41
5.7
[2.         2.64575131 2.82842712 1.73205081 1.         2.64575131
 2.64575131 3.         2.44948974 2.23606798]
[16 49 64  9  1 49 49 81 36 25]
[1 1 1 1 1 1 1 1 1 1]
9
1
7
4
6.5


In [4]:
# logarithmic fx
print(np.log(arr)) #base e ie natural log ln
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr)) # cal e ki power for each ele

[1.38629436 1.94591015 2.07944154 1.09861229 0.         1.94591015
 1.94591015 2.19722458 1.79175947 1.60943791]
[0.60205999 0.84509804 0.90308999 0.47712125 0.         0.84509804
 0.84509804 0.95424251 0.77815125 0.69897   ]
[2.         2.80735492 3.         1.5849625  0.         2.80735492
 2.80735492 3.169925   2.5849625  2.32192809]
[5.45981500e+01 1.09663316e+03 2.98095799e+03 2.00855369e+01
 2.71828183e+00 1.09663316e+03 1.09663316e+03 8.10308393e+03
 4.03428793e+02 1.48413159e+02]


In [5]:
 # round fxn
print(np.round(3.16))
print(np.round(3.66))
print(np.ceil(3.66))
print(np.floor(3.66))
print(np.trunc(3.66))

3.0
4.0
4.0
3.0
3.0


In [7]:
# other fxn
print(np.sort(arr))
print(np.unique(arr))
arr=np.array([-3,3,-1,0,7,-7])
print(np.abs(arr))

[1 3 4 5 6 7 7 7 8 9]
[1 3 4 5 6 7 8 9]
[3 3 1 0 7 7]
