In [1]:
import numpy as np

In [19]:
# creation
# 1-d array ; axes=0 : represent row
arr1D=np.array([1,2,3,4,5]) 
print(f"1D array : {arr1D} {arr1D.shape}")

#2-d array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]]) #3x3 : row x col
print(f"2D array : {arr2D} {arr2D.shape}")

# 3d array
arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2x2x3 : depth x row x column
print(f"3D array : {arr3D} {arr3D.shape}")

1D array : [1 2 3 4 5] (5,)
2D array : [[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
3D array : [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


### tasks :
1. get sum of whole matrix
2. get sum of each column and row

### basic undestanding of axis
#### 2d array :
- axis=0 : move in row-direction (ie left-to-right) ie col-wise 
- axis=1 : move in col-direction (ie top-to-bottom) ie row-wise
#### 3d array :
- axis=0 : move in layer-direction 
- axis=1 : move in row-direction (ie left-to-right) ie col-wise 
- axis=2 : move in col-direction (ie top-to-bottom) ie row-wise

In [45]:
print("2D: ",arr2D,sep="\n")
print("3D : ",arr3D,sep="\n")


2D: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3D : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
#1. whole sum
total_sum=np.sum(arr1D)
print(f"1d sum : {total_sum}")
total_sum=np.sum(arr2D)
print(f"2d sum : {total_sum}")
total_sum=np.sum(arr3D)
print(f"3d sum : {total_sum}")

1d sum : 15
2d sum : 45
3d sum : 78


In [47]:
#  column-row sum

# 2d array
col_sum=np.sum(arr2D,axis=0) #axis=0 : col-wise
row_sum=np.sum(arr2D,axis=1) #axis=1 : row-wise
print(col_sum)
print(row_sum)

print("3-D array------------------")
# 3d array
layer_sum=np.sum(arr3D,axis=0) #axis=0:layer-wise
col_sum=np.sum(arr3D,axis=1) #axis=1 : col-wise
row_sum=np.sum(arr3D,axis=2) #axis=2 : row-wise
print("Layer wise sum : ",layer_sum)
print("col wise sum : ",col_sum)
print("row wise sum : ",row_sum)

[12 15 18]
[ 6 15 24]
3-D array------------------
Layer wise sum :  [[ 8 10 12]
 [14 16 18]]
col wise sum :  [[ 5  7  9]
 [17 19 21]]
row wise sum :  [[ 6 15]
 [24 33]]


#### slicing / accessing particular row/col/ele in 2d and 3d array

In [48]:
print("2D: ",arr2D,sep="\n")
print("3D : ",arr3D,sep="\n")


2D: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3D : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
# slicing from 2d
print(arr2D[:2,1:2])
print()
print(arr2D[2:3,1:3])
print()
print(arr2D[1:2,:])
print()
print(arr2D[:,2:3])

[[2]
 [5]]

[[8 9]]

[[4 5 6]]

[[3]
 [6]
 [9]]


In [58]:

print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [64]:
# slicing from 3d array
print(arr3D[:,0:1,1:2])
print()
print(arr3D[0,1:2,:])
print()
print(arr3D[1,:,1])
print()
print(arr3D[0,1:2,2:3])
print()
print(arr3D[:,1:2,1:2])

[[[2]]

 [[8]]]

[[4 5 6]]

[ 8 11]

[[6]]

[[[ 5]]

 [[11]]]
