In [1]:
import numpy as np

In [2]:
# vectorization : instead of running loops on iterables(array) to perform operation, vectorization allow to perform task without loop
arr=np.array([4,5,3,7,1])
print(arr **2)

[16 25  9 49  1]


In [3]:
print(arr > 5)

[False False False  True False]


In [9]:
arr2=np.linspace(1,20,5,dtype="int64")
print(arr2)
print(arr+arr2)

[ 1  5 10 15 20]
[ 5 10 13 22 21]


In [12]:
# broadcasting : scaling smaller array to make compatible so that operations can take place
# broadcasting rules(general) : either arrays should bre of equal size or one of them has 1 means 1d array
arr=np.array([5,7,8,9,2,3])
num=5

print(arr+num)

[10 12 13 14  7  8]


In [20]:
# error prone broadcasting
arr1=np.array([4,6,2,4,5]) # (1,5)
arr2=np.full((3,2),100) # (3,2) 
print(arr1+arr2) # broadcast error

ValueError: operands could not be broadcast together with shapes (5,) (3,2) 

### vector Normalisation : application of broadcasting

- normalisation : transforming the values so that they can fit into a common scale

In [31]:
# standard Normalisation
# formula : arr-mean/std dev

arr=np.array([[2,6,5],[3,6,1]]) #2x3
mean=np.mean(arr)
print(mean)
std_dev=np.std(arr)
print(std_dev)
normalized_vector=(arr-mean)/std_dev
print(normalized_vector)
# mean of normalized_vector will be very close to 0 & std dev close to 1
print(np.mean(normalized_vector,dtype="int64"),np.std(normalized_vector),sep="\n")

3.8333333333333335
1.9507833184532708
[[-0.93979342  1.11066496  0.59805036]
 [-0.42717883  1.11066496 -1.45240802]]
0
1.0
